apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: local-

patches:
  - path: deployment.yaml
  - path: mongodb.yaml

configMapGenerator:
  - behavior: replace
    envs:
      - config.properties
    name: database-map

images:
  - name: webapp:latest
    newName: guestbookapp
    newTag: latest
