apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual-mongo-main
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
