apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: develop-

patches:
  - path: deployment.yaml
  - path: ingress.yaml

configMapGenerator:
  - behavior: replace
    envs:
      - config.properties
    name: database-map

images:
  - name: webapp:latest
    newName: lhr.ocir.io/lrhvckxzwf3l/guestbook
    newTag: 13e7df538cb4eaa4dd67b6d3371393d41fdaca80
