apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- pv.yaml
- pvc.yaml

namespace: guestbook-develop

patches:
- path: deployment.yaml
- path: ingress.yaml
- path: mongodb.yaml

configMapGenerator:
- behavior: replace
  envs:
  - config.properties
  name: database-map

images:
- name: webapp:latest
  newName: lhr.ocir.io/lrhvckxzwf3l/guestbook
  newTag: 0a6bb450917f980a14ca357972da8d483ecc9ba1
