apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-mongo-volume-develop
  labels:
    type: local
spec:
  storageClassName: manual-mongo-develop
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongodb/guestbook/develop"
